import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
	const router = useRouter()
	const handleGotoDetailsPost = () => {
		router.push({
			pathname: '/posts/[postId]',
			query: {
				postId: '123',
				ref: 'social',
			},
		})
	}
	return (
		<div className={styles.container}>
			<Head>
				<title>Learning NextJS</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<div
					style={{
						height: '100vh',
						width: '100vw',
						background: 'blue',
						padding: '1rem',
						color: 'white',
						display: 'flex',
						justifyContent: 'center',
						alignItems: 'center',
						margin: '1000px 0',
					}}
				>
					ABC
				</div>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
				<button className={styles.button}>
					<Link href="/about" prefetch>
						<a className={styles.link}>About Us</a>
					</Link>
				</button>
				<button className={styles.button} onClick={() => handleGotoDetailsPost()}>
					<p>Go to post details page</p>
				</button>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}

export default Home
